#!/usr/bin/env tsx
/**
 * Regenerates homepage/styles.css from the app's BRAND.md tokens (app/globals.css)
 * and the Tailwind classes used in homepage/*.html. The homepage is served as
 * plain static files, so the output is committed; rerun after editing the HTML.
 *
 * Usage:
 *   pnpm homepage:css
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import tailwind from "@tailwindcss/postcss";
import postcss from "postcss";

const APP_CSS = resolve("app/globals.css");
const OUT = resolve("homepage/styles.css");

// next/font supplies these variables in the app; the homepage self-hosts the same
// Latin variable fonts from homepage/fonts/.
const FONTS = `
@font-face { font-family: "Space Grotesk"; src: url("fonts/space-grotesk-latin.woff2") format("woff2"); font-weight: 300 700; font-display: swap; }
@font-face { font-family: "Geist"; src: url("fonts/geist-latin.woff2") format("woff2"); font-weight: 100 900; font-display: swap; }
@font-face { font-family: "JetBrains Mono"; src: url("fonts/jetbrains-mono-latin.woff2") format("woff2"); font-weight: 100 800; font-display: swap; }
@font-face { font-family: "symbols"; src: url("fonts/material-symbols-outlined.woff2") format("woff2"); font-weight: 400; font-display: block; }
:root {
  --font-grotesk: "Space Grotesk";
  --font-geist: "Geist";
  --font-jbm: "JetBrains Mono";
  --font-symbols: "symbols";
}
`;

async function build() {
  const appCss = readFileSync(APP_CSS, "utf8");
  const tailwindImport = '@import "tailwindcss";';
  if (!appCss.includes(tailwindImport)) {
    throw new Error(`${APP_CSS} no longer starts with ${tailwindImport}; update this script`);
  }
  // source(none) stops Tailwind scanning the whole repo; only the homepage HTML counts.
  const input = appCss.replace(
    tailwindImport,
    `@import "tailwindcss" source(none);\n@source "./*.html";\n${FONTS}`,
  );
  const result = await postcss([tailwind({ optimize: true })]).process(input, {
    from: OUT,
    to: OUT,
  });
  writeFileSync(
    OUT,
    `/* Generated by scripts/build-homepage-css.ts from app/globals.css. Do not edit. */\n${result.css}`,
  );
  console.log(`wrote ${OUT} (${(result.css.length / 1024).toFixed(1)} KB)`);
}

build().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
